version: '3.7'
services:
  osticket:
    image: pragosa/osticket:1.17
    container_name: OsTicket
    volumes:
      - css:/var/www/html/
      - attachements:/attachments
    restart: always
    ports:
      - 80
    environment:
      MYSQL_HOST: osticket-db
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: pragosa@tickets

  osticket-db:
    image: mysql:5.7
    container_name: OsTicketDB
    volumes:
      - /docker/osticket/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pragosa@tickets
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: pragosa@tickets

  osticket-pa:
     image: phpmyadmin/phpmyadmin
     container_name: OsTicketPA
     ports:
      - 80
     environment:
      PMA_HOSTS: osticket-db
      MYSQL_ROOT_PASSWORD: pragosa@tickets

volumes:
  css:
  attachments: